
- name: Install Flannel
  become: True
  become_user: "{{kubernetes_user}}"
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml

- name: Expose token and CA cert hash 
  become: True
  become_user: "{{kubernetes_user}}"
  shell: echo "KUBEADM JOIN URL:" && cat /tmp/k8s_install.log | grep "kubeadm join"